# frontend.py
import streamlit as st
import plotly.graph_objects as go
from datetime import datetime

from Backend import search_stocks_in_db, fetch_live_nse_quote, load_and_prepare_data, train_and_predict, fetch_option_chain


# Custom CSS styling
import streamlit as st
import yfinance as yf
import pandas as pd
import plotly.graph_objects as go
from nsepython import nse_optionchain_scrapper # or your custom backend import

# 1. Page Configuration & CSS Styling
st.set_page_config(page_title="Nifty 50 Dashboard", layout="wide")

st.markdown("""
<style>
    .stApp { background-color: #0b0e14; color: #e0e6ed; }
    div[data-testid="stMetric"] { background-color: #121721; border: 1px solid #1e293b; padding: 16px; border-radius: 12px; }
</style>
""", unsafe_allow_html=True)

st.title("NIFTY 50 Live Feed & Analytics")

# ---------------------------------------------------------
# 2. Live Market Data Fetcher
# ---------------------------------------------------------
def get_live_market_data(symbol_name):
    ticker_map = {
        "NIFTY 50": "^NSEI",
        "NIFTY BANK": "^NSEBANK",
        "FINNIFTY": "NIFTY_FIN_SERVICE.NS"
    }
    ticker_symbol = ticker_map.get(symbol_name, f"{symbol_name}.NS" if not symbol_name.startswith("^") else symbol_name)
    
    try:
        ticker = yf.Ticker(ticker_symbol)
        info = ticker.fast_info
        
        live_price = info.last_price or 0.0
        prev_close = info.previous_close or 0.0
        day_high = info.day_high or 0.0
        day_low = info.day_low or 0.0
        
        change = live_price - prev_close if prev_close else 0.0
        p_change = (change / prev_close * 100) if prev_close else 0.0
        
        return {
            "live_price": live_price,
            "day_high": day_high,
            "day_low": day_low,
            "prev_close": prev_close,
            "change": change,
            "p_change": p_change
        }
    except Exception as e:
        return {"live_price": 0.0, "day_high": 0.0, "day_low": 0.0, "prev_close": 0.0, "change": 0.0, "p_change": 0.0}

# ---------------------------------------------------------
# 3. Metric Containers Top Bar
# ---------------------------------------------------------
selected_stock = "NIFTY 50" 
predicted_price = 24250.50 # Connect to your ML model prediction

market_data = get_live_market_data(selected_stock)

live_price = market_data["live_price"]
day_high = market_data["day_high"]
day_low = market_data["day_low"]
prev_close = market_data["prev_close"]
change = market_data["change"]
p_change = market_data["p_change"]

pred_diff = predicted_price - live_price if live_price > 0 else 0.0
pred_diff_pct = (pred_diff / live_price * 100) if live_price > 0 else 0.0

col1, col2, col3, col4, col5 = st.columns(5)

with col1:
    st.metric("Live Price", f"₹{live_price:,.2f}", f"{change:+.2f} ({p_change:+.2f}%)")
with col2:
    st.metric("Day High", f"₹{day_high:,.2f}")
with col3:
    st.metric("Day Low", f"₹{day_low:,.2f}")
with col4:
    st.metric("Prev Close", f"₹{prev_close:,.2f}")
with col5:
    st.metric("Predicted Diff", f"₹{pred_diff:,.2f}", f"{pred_diff_pct:+.2f}% Target")

st.markdown("---")

# ---------------------------------------------------------
# 4. Traditional Candlestick Chart Section
# ---------------------------------------------------------
st.subheader("Price Chart & Prediction Overlay")

# Fetch Historical Data for Chart
chart_df = yf.download("^NSEI", period="5d", interval="15m").reset_index()

if not chart_df.empty:
    # Handle multi-level columns if generated by yfinance
    if isinstance(chart_df.columns, pd.MultiIndex):
        chart_df.columns = chart_df.columns.get_level_values(0)
        
    chart_df['SMA_20'] = chart_df['Close'].rolling(window=20).mean()

    fig = go.Figure()

    # Candlesticks
    fig.add_trace(go.Candlestick(
        x=chart_df['Datetime'] if 'Datetime' in chart_df.columns else chart_df['Date'],
        open=chart_df['Open'], high=chart_df['High'], low=chart_df['Low'], close=chart_df['Close'],
        name='Price', increasing_line_color='#00d09c', decreasing_line_color='#eb5757'
    ))

    # 20 SMA Line
    fig.add_trace(go.Scatter(
        x=chart_df['Datetime'] if 'Datetime' in chart_df.columns else chart_df['Date'],
        y=chart_df['SMA_20'], mode='lines', name='20 SMA', line=dict(color='#5D6D7E', width=1.5)
    ))

    # Prediction Projection Marker
    if live_price > 0:
        last_time = chart_df['Datetime'].iloc[-1] if 'Datetime' in chart_df.columns else chart_df['Date'].iloc[-1]
        fig.add_trace(go.Scatter(
            x=[last_time], y=[predicted_price],
            mode='markers+text', name='Predicted Target',
            text=[f"Target: ₹{predicted_price:,.2f}"], textposition="top center",
            marker=dict(size=10, color='#00d09c' if pred_diff >= 0 else '#eb5757', symbol='star')
        ))

    fig.update_layout(
        template='plotly_dark', paper_bgcolor='#0b0e14', plot_bgcolor='#0b0e14',
        xaxis_rangeslider_visible=False, margin=dict(l=10, r=10, t=30, b=10)
    )
    st.plotly_chart(fig, use_container_width=True)

st.markdown("---")

# ---------------------------------------------------------
# 5. Option Chain Section (Restored)
# ---------------------------------------------------------
st.subheader("Option Chain Data")
import streamlit as st
import plotly.graph_objects as go
from Backend import fetch_option_chain

# --- OPTION CHAIN SECTION ---
st.subheader("Option Chain Analysis")
symbol = st.text_input("Enter NSE Ticker (e.g. NIFTY, RELIANCE):", value="NIFTY")

if st.button("Fetch Option Chain"):
  # Fetch Option Chain Data
df_oc = fetch_option_chain(symbol)

# Safely check if data was successfully fetched
if df_oc is not None and isinstance(df_oc, pd.DataFrame) and not df_oc.empty:
    st.dataframe(df_oc)
    
    # Plotting code here...
else:
    st.warning(f"Could not fetch option chain data for '{symbol}'. NSE servers may be blocking requests or the symbol may be invalid.")
import streamlit as st
import yfinance as yf

# 1. Define a list of popular symbols or load them from your SQLite DB
STOCK_LIST = [
    "NIFTY 50",
    "NIFTY BANK",
    "FINNIFTY",
    "RELIANCE",
    "TCS",
    "INFY",
    "HDFCBANK",
    "ICICIBANK",
    "SBIN",
    "BHARTIARTL",
    "ITC",
    "TATAMOTORS"
    "TechMahindra"
    "HCLTECH"
]



# The user can type into this box to instantly search and autocomplete symbols
selected_stock = st.sidebar.selectbox(
    label="Search or Select Stock / Index",
    options=STOCK_LIST,
    index=0,  # Defaults to NIFTY 50
    help="Type to search for NSE stocks or major indices"
)

# 3. Dynamic Ticker Resolver for yfinance & NSE APIs
def resolve_ticker(symbol):
    ticker_map = {
        "NIFTY 50": "^NSEI",
        "NIFTY BANK": "^NSEBANK",
        "FINNIFTY": "NIFTY_FIN_SERVICE.NS"
    }
    # If it's an index, map it; if it's an NSE equity, append .NS
    if symbol in ticker_map:
        return ticker_map[symbol]
    elif not symbol.startswith("^") and not symbol.endswith(".NS"):
        return f"{symbol}.NS"
    return symbol

# Resolve selected symbol
active_ticker = resolve_ticker(selected_stock)

# Display Active Stock Header
st.title(f"📊 Market Analysis: {selected_stock}")

st.markdown("""""
<style>
    .stApp { background-color: #0b0e14; color: #e0e6ed; }
    div[data-testid="stMetric"] { background-color: #121721; border: 1px solid #1e293b; padding: 16px; border-radius: 12px; }
    .groww-badge-green { background-color: rgba(0, 208, 156, 0.15); color: #00d09c; border: 1px solid #00d09c; padding: 6px 14px; border-radius: 20px; font-weight: bold; display: inline-block; }
    .groww-badge-red { background-color: rgba(235, 87, 87, 0.15); color: #eb5757; border: 1px solid #eb5757; padding: 6px 14px; border-radius: 20px; font-weight: bold; display: inline-block; }
</style>
""", unsafe_allow_html=True)

st.title("📈 Candlytix Terminal & Option Chain Visualizer")

import streamlit as st
import yfinance as yf

# ---------------------------------------------------------
# 1. Reliable Data Fetcher with Symbol Mapper
# ---------------------------------------------------------
def get_live_market_data(symbol_name):
    # Map friendly names to correct yfinance tickers
    ticker_map = {
        "NIFTY 50": "^NSEI",
        "NIFTY BANK": "^NSEBANK",
        "FINNIFTY": "NIFTY_FIN_SERVICE.NS"
    }
    
    # If symbol is a normal stock (e.g. RELIANCE), append .NS
    ticker_symbol = ticker_map.get(symbol_name, f"{symbol_name}.NS" if not symbol_name.startswith("^") else symbol_name)
    
    try:
        ticker = yf.Ticker(ticker_symbol)
        # Use fast_info for real-time market data
        info = ticker.fast_info
        
        live_price = info.last_price or 0.0
        prev_close = info.previous_close or 0.0
        day_high = info.day_high or 0.0
        day_low = info.day_low or 0.0
        
        change = live_price - prev_close if prev_close else 0.0
        p_change = (change / prev_close * 100) if prev_close else 0.0
        
        return {
            "live_price": live_price,
            "day_high": day_high,
            "day_low": day_low,
            "prev_close": prev_close,
            "change": change,
            "p_change": p_change
        }
    except Exception as e:
        st.error(f"Error fetching data for {symbol_name}: {e}")
        return {"live_price": 0.0, "day_high": 0.0, "day_low": 0.0, "prev_close": 0.0, "change": 0.0, "p_change": 0.0}

# ---------------------------------------------------------
# 2. UI Container Display in Streamlit
# ---------------------------------------------------------
# Example Inputs
selected_stock = "NIFTY 50" 
predicted_price = 24850.50 # Replace with your model's output variable

# Fetch real-time data
market_data = get_live_market_data(selected_stock)

live_price = market_data["live_price"]
day_high = market_data["day_high"]
day_low = market_data["day_low"]
prev_close = market_data["prev_close"]
change = market_data["change"]
p_change = market_data["p_change"]


# Render 5 Equal Columns
col1, col2, col3, col4, col5 = st.columns(5)

with col1:
    st.metric(
        label="Live Price", 
        value=f"₹{live_price:,.2f}", 
        delta=f"{change:+.2f} ({p_change:+.2f}%)"
    )

with col2:
    st.metric(
        label="Day High", 
        value=f"₹{day_high:,.2f}"
    )

with col3:
    st.metric(
        label="Day Low", 
        value=f"₹{day_low:,.2f}"
    )

with col4:
    st.metric(
        label="Prev Close", 
        value=f"₹{prev_close:,.2f}"
    )

# NEW: Predicted Difference Container
with col5:
    st.metric(
        label="Predicted Diff", 
        value=f"₹{pred_diff:,.2f}", 
        delta=f"{pred_diff_pct:+.2f}% Target"
    )

    import streamlit as st
import yfinance as yf
import pandas as pd
import plotly.graph_objects as go
import sqlite3

# 1. PAGE CONFIG
st.set_page_config(page_title="Nifty 50 Dashboard", layout="wide")


# =========================================================
# STEP 3: (Optional) LOAD ALL STOCKS FROM DATABASE
# Place helper functions at the top before rendering the UI
# =========================================================
def load_stock_list_from_db():
    try:
        conn = sqlite3.connect("stocks.db")  # Replace with your db name
        cursor = conn.cursor()
        cursor.execute("SELECT symbol FROM stocks_table ORDER BY symbol ASC")
        rows = cursor.fetchall()
        conn.close()
        return [r[0] for r in rows]
    except Exception:
        # Default list if database isn't connected
        return ["NIFTY 50", "NIFTY BANK", "RELIANCE", "TCS", "INFY", "HDFCBANK", "SBIN"]

def resolve_ticker(symbol):
    ticker_map = {
        "NIFTY 50": "^NSEI",
        "NIFTY BANK": "^NSEBANK",
        "FINNIFTY": "NIFTY_FIN_SERVICE.NS"
    }
    if symbol in ticker_map:
        return ticker_map[symbol]
    elif not symbol.startswith("^") and not symbol.endswith(".NS"):
        return f"{symbol}.NS"
    return symbol


# =========================================================
# STEP 2: DATA FETCHER WITH CACHING
# =========================================================
@st.cache_data(ttl=15)
def get_stock_data(ticker):
    try:
        t = yf.Ticker(ticker)
        info = t.fast_info
        return {
            "price": info.last_price or 0.0,
            "prev_close": info.previous_close or 0.0,
            "high": info.day_high or 0.0,
            "low": info.day_low or 0.0
        }
    except Exception as e:
        return {"price": 0.0, "prev_close": 0.0, "high": 0.0, "low": 0.0}


# =========================================================
# STEP 1: SEARCH BAR UI (In Sidebar or Top)
# =========================================================
STOCK_LIST = load_stock_list_from_db()

st.sidebar.header("🔍 Stock Search")
selected_stock = st.sidebar.selectbox(
    label="Search or Select Stock / Index",
    options=STOCK_LIST,
    index=0
)

# Resolve selected symbol and fetch live data
active_ticker = resolve_ticker(selected_stock)
live_data = get_stock_data(active_ticker)


# =========================================================
# DISPLAY RESULTS IN YOUR METRIC CONTAINERS
# =========================================================
st.title(f"📊 Market Analysis: {selected_stock}")

live_price = live_data["price"]
day_high = live_data["high"]
day_low = live_data["low"]
prev_close = live_data["prev_close"]

change = live_price - prev_close if prev_close else 0.0
p_change = (change / prev_close * 100) if prev_close else 0.0

# Connect your ML Model prediction here
predicted_price = 24250.50 
pred_diff = predicted_price - live_price if live_price > 0 else 0.0
pred_diff_pct = (pred_diff / live_price * 100) if live_price > 0 else 0.0

col1, col2, col3, col4, col5 = st.columns(5)

with col1:
    st.metric("Live Price", f"₹{live_price:,.2f}", f"{change:+.2f} ({p_change:+.2f}%)")
with col2:
    st.metric("Day High", f"₹{day_high:,.2f}")
with col3:
    st.metric("Day Low", f"₹{day_low:,.2f}")
with col4:
    st.metric("Prev Close", f"₹{prev_close:,.2f}")
with col5:
    st.metric("Predicted Diff", f"₹{pred_diff:,.2f}", f"{pred_diff_pct:+.2f}% Target")

   
